// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmfC6D1MQl67YuaS-vsPGsugSsgPsu_w',
    appId: '1:978453510316:web:81c1ab9522cbceeb040709',
    messagingSenderId: '978453510316',
    projectId: 'atel-me',
    authDomain: 'atel-me.firebaseapp.com',
    storageBucket: 'atel-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9ovq_dGE9yLg8EIbEtf3jtnd62LckWw',
    appId: '1:978453510316:android:d68d38266db5b800040709',
    messagingSenderId: '978453510316',
    projectId: 'atel-me',
    storageBucket: 'atel-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhX9GGet0BBupAIe-sqKK1U6KAv3MpEM',
    appId: '1:978453510316:ios:e9154d42cf433275040709',
    messagingSenderId: '978453510316',
    projectId: 'atel-me',
    storageBucket: 'atel-me.firebasestorage.app',
    iosBundleId: 'com.auth.atel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhX9GGet0BBupAIe-sqKK1U6KAv3MpEM',
    appId: '1:978453510316:ios:d3c5009839104e22040709',
    messagingSenderId: '978453510316',
    projectId: 'atel-me',
    storageBucket: 'atel-me.firebasestorage.app',
    iosBundleId: 'com.example.atel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmfC6D1MQl67YuaS-vsPGsugSsgPsu_w',
    appId: '1:978453510316:web:cf87b0e412c3c340040709',
    messagingSenderId: '978453510316',
    projectId: 'atel-me',
    authDomain: 'atel-me.firebaseapp.com',
    storageBucket: 'atel-me.firebasestorage.app',
  );

}