// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyiIhCOkOM1fq812YpZQDRBeT35AJDdSU',
    appId: '1:581066014283:web:f5af7c3a11c4946d0757ce',
    messagingSenderId: '581066014283',
    projectId: 'auth-atel',
    authDomain: 'auth-atel.firebaseapp.com',
    storageBucket: 'auth-atel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK65k3isryAKQFm7BagRRjAQEb_Sqc0fw',
    appId: '1:581066014283:android:af549dcd8b1e29a40757ce',
    messagingSenderId: '581066014283',
    projectId: 'auth-atel',
    storageBucket: 'auth-atel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxSL0wfe6MZUDsBQhF1s92tv-FDEfM8s',
    appId: '1:581066014283:ios:91d7a2d4b067b4990757ce',
    messagingSenderId: '581066014283',
    projectId: 'auth-atel',
    storageBucket: 'auth-atel.firebasestorage.app',
    iosBundleId: 'com.auth.atel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxSL0wfe6MZUDsBQhF1s92tv-FDEfM8s',
    appId: '1:581066014283:ios:16eb19a3f469f2ef0757ce',
    messagingSenderId: '581066014283',
    projectId: 'auth-atel',
    storageBucket: 'auth-atel.firebasestorage.app',
    iosBundleId: 'com.example.atel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyiIhCOkOM1fq812YpZQDRBeT35AJDdSU',
    appId: '1:581066014283:web:80edd736600f39380757ce',
    messagingSenderId: '581066014283',
    projectId: 'auth-atel',
    authDomain: 'auth-atel.firebaseapp.com',
    storageBucket: 'auth-atel.firebasestorage.app',
  );
}
